//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genix.DocumentAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genix.DocumentAnalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough data with ground truth to train the classifier..
        /// </summary>
        internal static string E_Classifier_EmptyTrainset {
            get {
                return ResourceManager.GetString("E_Classifier_EmptyTrainset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The classifier is not ready. You have to learn the classifier before using it..
        /// </summary>
        internal static string E_Classifier_NotLearned {
            get {
                return ResourceManager.GetString("E_Classifier_NotLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image depth {0} is not supported for this operation..
        /// </summary>
        internal static string E_UnsupportedDepth {
            get {
                return ResourceManager.GetString("E_UnsupportedDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation supports binary (1bpp) images only..
        /// </summary>
        internal static string E_UnsupportedDepth_1bpp {
            get {
                return ResourceManager.GetString("E_UnsupportedDepth_1bpp", resourceCulture);
            }
        }
    }
}
