
// -----------------------------------------------------------------------
// <copyright file="Morphology.cs" company="Noname, Inc.">
// Copyright (c) 2018, Alexander Volgunin. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//     Generated on: 9/19/2018 3:40:58 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. Re-run the T4 template to update this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genix.Imaging
{
    public partial class Image
    {

        /// <summary>
        /// Dilates this <see cref="Image"/> by using the specified structuring element not-in-place.
        /// </summary>
        /// <param name="kernel">The structuring element used in this operation.</param>
        /// <param name="iterations">The number of times the operation is applied.</param>
        /// <returns>
        /// The new <see cref="Image"/>.
        /// </returns>
        /// <seealso cref="DilateIP(StructuringElement, int)"/>
        public Image Dilate(StructuringElement kernel, int iterations)
        {
            Image dst = this.Copy();
            dst.DilateIP(kernel, iterations);
            return dst;
        }

        /// <summary>
        /// Erodes this <see cref="Image"/> by using the specified structuring element not-in-place.
        /// </summary>
        /// <param name="kernel">The structuring element used in this operation.</param>
        /// <param name="iterations">The number of times the operation is applied.</param>
        /// <returns>
        /// The new <see cref="Image"/>.
        /// </returns>
        /// <seealso cref="ErodeIP(StructuringElement, int)"/>
        public Image Erode(StructuringElement kernel, int iterations)
        {
            Image dst = this.Copy();
            dst.ErodeIP(kernel, iterations);
            return dst;
        }

        /// <summary>
        /// Perform morphological opening operation on this <see cref="Image"/> by using the specified structuring element not-in-place.
        /// </summary>
        /// <param name="kernel">The structuring element used in this operation.</param>
        /// <param name="iterations">The number of times the operation is applied.</param>
        /// <returns>
        /// The new <see cref="Image"/>.
        /// </returns>
        /// <seealso cref="MorphOpenIP(StructuringElement, int)"/>
        public Image MorphOpen(StructuringElement kernel, int iterations)
        {
            Image dst = this.Copy();
            dst.MorphOpenIP(kernel, iterations);
            return dst;
        }

        /// <summary>
        /// Perform morphological closing operation on this <see cref="Image"/> by using the specified structuring element not-in-place.
        /// </summary>
        /// <param name="kernel">The structuring element used in this operation.</param>
        /// <param name="iterations">The number of times the operation is applied.</param>
        /// <returns>
        /// The new <see cref="Image"/>.
        /// </returns>
        /// <seealso cref="MorphCloseIP(StructuringElement, int)"/>
        public Image MorphClose(StructuringElement kernel, int iterations)
        {
            Image dst = this.Copy();
            dst.MorphCloseIP(kernel, iterations);
            return dst;
        }

        /// <summary>
        /// Removes small isolated pixels from this <see cref="Image"/> not-in-place.
        /// </summary>
        /// <returns>
        /// The new <see cref="Image"/>.
        /// </returns>
        /// <seealso cref="DespeckleIP()"/>
        public Image Despeckle()
        {
            Image dst = this.Copy();
            dst.DespeckleIP();
            return dst;
        }
	}
}