//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//     Generated on: 11/27/2018 8:05:39 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. Re-run the T4 template to update this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genix.Geometry.Test
{
    using System;
    using System.Linq;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class LineTest
    {

        [TestMethod]
        public void PerpendicularTest_int()
        {
            Line line1 = new Line(1, 2, 3, 4);
            Line line2 = line1.Perpendicular(5, 6);
            Assert.AreEqual(-1.0 / line1.M, line2.M);
        }

        [TestMethod]
        public void PerpendicularTest_float()
        {
            LineF line1 = new LineF(1, 2, 3, 4);
            LineF line2 = line1.Perpendicular(5, 6);
            Assert.AreEqual(-1.0 / line1.M, line2.M);
        }

        [TestMethod]
        public void PerpendicularTest_double()
        {
            LineD line1 = new LineD(1, 2, 3, 4);
            LineD line2 = line1.Perpendicular(5, 6);
            Assert.AreEqual(-1.0 / line1.M, line2.M);
        }
    }
}