// -----------------------------------------------------------------------
// <copyright file="TestImage.cs" company="Noname, Inc.">
// Copyright (c) 2018, Alexander Volgunin. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Genix.Imaging.Lab
{
    using System.Drawing;
    using Genix.Core;

    /// <summary>
    /// Represents a test image generated by the <see cref="TestImageProvider{TLabel}"/>.
    /// </summary>
    public class TestImage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestImage" /> class.
        /// </summary>
        /// <param name="sourceId">The information about image source.</param>
        /// <param name="font">The font used to generate the image.</param>
        /// <param name="fontStyle">The font style used to generate the image.</param>
        /// <param name="image">The generated image.</param>
        /// <param name="labels">The classification labels associated with the image.</param>
        public TestImage(DataSourceId sourceId, string font, FontStyle? fontStyle, Genix.Imaging.Image image, string[] labels)
        {
            this.SourceId = sourceId;
            this.Font = font;
            this.FontStyle = fontStyle;
            this.Image = image;
            this.Labels = labels;
        }

        /// <summary>
        /// Gets the image source id.
        /// </summary>
        /// <value>
        /// A <see cref="DataSourceId"/> that contains the information about image source.
        /// </value>
        public DataSourceId SourceId { get; }

        /// <summary>
        /// Gets the font used to generate the image.
        /// </summary>
        /// <value>
        /// The font used to generate the image.
        /// </value>
        public string Font { get; }

        /// <summary>
        /// Gets the font style used to generate the image.
        /// </summary>
        /// <value>
        /// The font style used to generate the image.
        /// </value>
        public FontStyle? FontStyle { get; }

        /// <summary>
        /// Gets the generated image.
        /// </summary>
        /// <value>
        /// The generated image.
        /// </value>
        public Genix.Imaging.Image Image { get; }

        /// <summary>
        /// Gets the classification labels associated with the image.
        /// </summary>
        /// <value>
        /// The classification labels associated with the image.
        /// </value>
        public string[] Labels { get; }
    }
}
